
#include "IBMFDriver/IBMFFont.hpp"
#include "IBMFDriver/IBMFFontLow.hpp"
#include "IBMFFonts/EC-Regular_75.h"

IBMFFontLow EC_Regular_75 = IBMFFontLow();

IBMFFont FONT_EC_REGULAR_75BPI12PT =
    IBMFFont(EC_Regular_75, EC_REGULAR_75_IBMF, EC_REGULAR_75_IBMF_LEN, 0);
IBMFFont FONT_EC_REGULAR_75BPI14PT =
    IBMFFont(EC_Regular_75, EC_REGULAR_75_IBMF, EC_REGULAR_75_IBMF_LEN, 1);
IBMFFont FONT_EC_REGULAR_75BPI17PT =
    IBMFFont(EC_Regular_75, EC_REGULAR_75_IBMF, EC_REGULAR_75_IBMF_LEN, 2);