#include <cinttypes>

#include "IBMFDriver/IBMFFont.hpp"
#include "IBMFDriver/IBMFFontLow.hpp"

#include "IBMFFonts/EC-Regular_75.h"

IBMFFontLow EC_Regular_75 = IBMFFontLow();

IBMFFont FONT_EC_REGULAR_75BPI12PT =
    IBMFFont(EC_Regular_75, EC_REGULAR_75_IBMF, EC_REGULAR_75_IBMF_LEN, 0);
IBMFFont FONT_EC_REGULAR_75BPI14PT =
    IBMFFont(EC_Regular_75, EC_REGULAR_75_IBMF, EC_REGULAR_75_IBMF_LEN, 1);
IBMFFont FONT_EC_REGULAR_75BPI17PT =
    IBMFFont(EC_Regular_75, EC_REGULAR_75_IBMF, EC_REGULAR_75_IBMF_LEN, 2);

#include "IBMFFonts/EC-Regular_100.h"

IBMFFontLow EC_Regular_100 = IBMFFontLow();

IBMFFont FONT_EC_REGULAR_100BPI12PT =
    IBMFFont(EC_Regular_100, EC_REGULAR_100_IBMF, EC_REGULAR_100_IBMF_LEN, 0);
IBMFFont FONT_EC_REGULAR_100BPI14PT =
    IBMFFont(EC_Regular_100, EC_REGULAR_100_IBMF, EC_REGULAR_100_IBMF_LEN, 1);
IBMFFont FONT_EC_REGULAR_100BPI17PT =
    IBMFFont(EC_Regular_100, EC_REGULAR_100_IBMF, EC_REGULAR_100_IBMF_LEN, 2);

#include "IBMFFonts/ECSans-Regular_75.h"

IBMFFontLow ECSans_Regular_75 = IBMFFontLow();

IBMFFont FONT_ECSANS_REGULAR_75BPI12PT =
    IBMFFont(ECSans_Regular_75, ECSANS_REGULAR_75_IBMF, ECSANS_REGULAR_75_IBMF_LEN, 0);
IBMFFont FONT_ECSANS_REGULAR_75BPI14PT =
    IBMFFont(ECSans_Regular_75, ECSANS_REGULAR_75_IBMF, ECSANS_REGULAR_75_IBMF_LEN, 1);
IBMFFont FONT_ECSANS_REGULAR_75BPI17PT =
    IBMFFont(ECSans_Regular_75, ECSANS_REGULAR_75_IBMF, ECSANS_REGULAR_75_IBMF_LEN, 2);

#include "IBMFFonts/ECSans-Regular_100.h"

IBMFFontLow ECSans_Regular_100 = IBMFFontLow();

IBMFFont FONT_ECSANS_REGULAR_100BPI12PT =
    IBMFFont(ECSans_Regular_100, ECSANS_REGULAR_100_IBMF, ECSANS_REGULAR_100_IBMF_LEN, 0);
IBMFFont FONT_ECSANS_REGULAR_100BPI14PT =
    IBMFFont(ECSans_Regular_100, ECSANS_REGULAR_100_IBMF, ECSANS_REGULAR_100_IBMF_LEN, 1);
IBMFFont FONT_ECSANS_REGULAR_100BPI17PT =
    IBMFFont(ECSans_Regular_100, ECSANS_REGULAR_100_IBMF, ECSANS_REGULAR_100_IBMF_LEN, 2);